version: "3"
networks:
  infura:
services:
  mysql:
    restart: always
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: 'Asia/Taipei'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: '1234'
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - infura
    restart: always
  redis:
    image: redis:3.2
    volumes:
      - ../redis/redis.conf:/etc/redis/redis.conf:ro
      - ../redis/data:/data
    command:
      - redis-server
      - /etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always
    networks:
      - infura
  fastdfs:
    build: ../fastdfs
    image: xsj/fastdfs:5.11
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    container_name: fastdfs
    environment:
    # nginx服务端口
    - WEB_PORT=8888
    # fdfs服务端口
    - FDFS_PORT=22122
    # 默认fastdfs storage server 端口
    - STORAGE_PORT=23000
    # docker所在主机的IP地址
    - IP=内网ip
    volumes:
    # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
    - /usr/local/data/fastdfs:/var/local/fdfs
    # 使docker具有root权限以读写主机上的目录
    privileged: true
    # 网络模式为host，即直接使用主机的网络接口
    network_mode: "host"
volumes:
  mysql-data: